######## by Feng Ju, eawag, July 30, 2018
##Index Reference

##Sample list
##ls genes/*.fna | sed 's/.fna//'> sample_list.txt
#!/bin/bash
#BSUB -J "Usearch[1-2]%2"
#BSUB -R "rusage[mem=1000]"
#BSUB -n 1
#BSUB -W 1:00
#BSUB -R "rusage[scratch=1000]"

#####Definition of the paths

data="/cluster/project/gdc/people/fengju/example/genes/"
path_out="/cluster/project/gdc/people/fengju/example/genes/"

IDX=$LSB_JOBINDEX
name=`sed -n ${IDX}p < /cluster/project/gdc/people/fengju/example/genes/sample_list.txt`

module load blast/2.2.30

blastp -query ${data}${name}.fna -db databases/SARG_20170328.fasta -out ${data}${name}.SARG.blastp -evalue 1e-5 -max_target_seqs 1 -num_threads 1 -outfmt 6

